name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}

      - name: Type Check
        run: npm run type-check

      - name: Lint
        run: npm run lint

      - name: Run Tests
        run: npm run test:ci

      - name: Build Application (only on master)
        if: github.ref == 'refs/heads/master'
        run: npm run build

      - name: Upload Build Artifacts (only on master)
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ github.sha }}
          path: dist/
          retention-days: 7 